### ISSUE TITLE
Cant use Buckets In New Worlds

### ISSUE THREAD

**Issue by Ruok2bu** [Multiverse/Multiverse-Core#1042]
I have a creative flat world and survival normal on my server that i just generated yesterday and today respectively and no one (including myself who has the highest permissions) can use buckets of water or buckets of lava.  The moment its used, the water disappears.  if a bucket is used on water in an ocean or other body of water, the water disappears in that block and the surrounding water doesnt rush in. On my other worlds which were imported or generated in an older version of craftbukkit and multiverse, im able to use them fine.

Any idea why its doing this?

I'm using Multiverse-Core 2.5-b654 with CraftBukkit 1.4.6-R0.3

P.S. I narrowed down the problem specifically to this plugin.

My World entry is:

```
  Hosted_Gandolin:
    ==: MVWorld
    hidden: 'false'
    alias: gandolin
    color: GRAY
    style: NORMAL
    pvp: 'false'
    scale: '1.0'
    respawnWorld: ''
    allowWeather: 'false'
    difficulty: NORMAL
    spawning:
      ==: MVSpawnSettings
      animals:
        ==: MVSpawnSubSettings
        spawn: 'false'
        spawnrate: '-1'
        exceptions: []
      monsters:
        ==: MVSpawnSubSettings
        spawn: 'false'
        spawnrate: '-1'
        exceptions: []
    entryfee:
      ==: MVEntryFee
      amount: '0.0'
      currency: '-1'
    hunger: 'false'
    autoHeal: 'true'
    adjustSpawn: 'false'
    portalForm: ALL
    gameMode: CREATIVE
    keepSpawnInMemory: 'false'
    spawnLocation:
      ==: MVSpawnLocation
      yaw: 0.0
      pitch: 0.0
      z: -1158.0
      y: 4.0
      x: 848.0
    autoLoad: 'true'
    bedRespawn: 'true'
    worldBlacklist: []
    environment: NORMAL
    seed: '8978812179283032967'
    generator: 'null'
    playerLimit: '-1'
    allowFlight: 'true'
```
