### ISSUE TITLE
Trouble Understanding Permissions

### ISSUE THREAD

**Issue by ub1quit33** [Multiverse/Multiverse-Core#1052]
I'm trying to setup teleportation permissions for my players. I can't seem to figure out the correct permissions to grant. Here is an example of my configuration

```yaml
builder:
    permissions:
        - multiverse.access.world\.classic: true
        - multiverse.teleport.self.world\.classic: true
```

The world I'm trying to grant permission to is named world.classic, hence my \ escape.

When the players try to teleport with this permission, they get an error saying they have none of the necessary permissions, and then names parameters such as ```multiverse.teleport.self.w``` and ```multiverse.teleport.self.ca```. Are these automatically assigned aliases for my worlds? If so, how do I determine which alias goes to which world?
