### ISSUE TITLE
Default World-Nether Portal linking behavior

### ISSUE THREAD

**Issue by durand1w** [Multiverse/Multiverse-Core#1152]
I am running CraftBukkit Beta Build (1.5.1-R0.1) with the lastest Multiverse-Core build 665.  Nether Portals are able to generate portals in the nether, but the portals do not link back to the overworld.  I have attempted to modify and test the defaultportalsearch (true and false) and portalsearchradius (16 and 128) without any luck.  This was also an issue in 1.4 for which a newer version of Mutiverse was indicated as the solution.

Are there any other settings to have Multiverse use the default portal behavior and linking?  We are only running 1 additional skylands world.

```
multiverse-configuration:
  ==: com.onarandombox.MultiverseCore.MultiverseCoreConfiguration
  enforceaccess: 'false'
  prefixchat: 'true'
  useasyncchat: 'true'
  teleportintercept: 'true'
  firstspawnoverride: 'true'
  displaypermerrors: 'true'
  globaldebug: '0'
  silentstart: 'false'
  messagecooldown: '5000'
  version: '2.9'
  firstspawnworld: world
  teleportcooldown: '1000'
  defaultportalsearch: 'false'
  portalsearchradius: '16'
```
