### ISSUE TITLE
Chicken jockeys and mob spawning: false

### ISSUE THREAD

**Issue by MarioG1** [Multiverse/Multiverse-Core#1424]
Since minecraft 1.7.4 chicken jockeys can spawn naturally. Due to the fact that this is some kind of stacked entity (mob and animal) the chicken span isn't cancelled when a chicken jokey tries to spawn if spawn monsters is set to false which leads to an huge amount of chickens in an short time.....

How to reproduce it:

Config example:

```
    difficulty: HARD
    spawning:
      ==: MVSpawnSettings
      animals:
        ==: MVSpawnSubSettings
        spawn: 'true'
        spawnrate: '-1'
        exceptions: []
      monsters:
        ==: MVSpawnSubSettings
        spawn: 'false'
        spawnrate: '-1'
        exceptions: []
```

If you got to the nether (or normal world but its much easier to notice in the nether) chickens will start to spawn.

Some example code how to determine if the chicken is an chicken jockey chicken:

``` java
        LivingEntity suspect = event.getEntity();
        if(suspect instanceof Chicken)
        {
            List nearbyMobs = suspect.getNearbyEntities(0.5D, 1.0D, 0.5D);
            Iterator nearbyMobIterator = nearbyMobs.iterator();
            boolean foundZombie = false;
            Entity result = null;
            while(nearbyMobIterator.hasNext()) 
            {
                result = (Entity)nearbyMobIterator.next();
                if((result instanceof Zombie) || (result instanceof PigZombie))
                    foundZombie = true;
            }
            if(foundZombie)
                suspect.setRemoveWhenFarAway(true);
        }
```
