### ISSUE TITLE
Health Regeneration Broken?

### ISSUE THREAD

**Issue by lexi-lambda** [Multiverse/Multiverse-Core#150]
As soon as I updated to RB 1185, it seems that health regen broke. I'm running Bukkit 1185 and MV b271. Here's my world's config:

```
creative:
    environment: NORMAL
    animals:
        spawn: true
        exceptions:
    monsters:
        spawn: false
        enforced: true
        exceptions:
    pvp: false
    seed: ''
    alias:
        color: GREEN
        name: Creative
    scale: 1.0
    respawnworld: creative
    allowweather: true
    entryfee:
        amount: 0.0
        currency: -1
    keepspawninmemory: true
    tempspawn: ''
    spawn:
        yaw: 0.0
        pitch: 0.0
        z: 240.0
        y: 73.0
        x: 192.0
    hunger: true
    gamemode: SURVIVAL
```

Any ideas?
