### ISSUE TITLE
respawnWorld not working (No EssentialsSpawn)

### ISSUE THREAD

**Issue by SmartSoda** [Multiverse/Multiverse-Core#1577]
The flag in the world configuration, respawnWorld, does not seem to work for me.
Yes, I am using Essentials, but only Essentials, excluding the addons like EssentialsSpawn.

Here is an example of one of the worlds.
```

KitPvP:
    ==: MVWorld
    hidden: 'false'
    alias: KitPvP
    color: WHITE
    style: NORMAL
    pvp: 'false'
    scale: '1.0'
    respawnWorld: KitPvP-Lobby
    allowWeather: 'false'
    difficulty: EASY
    spawning:
      ==: MVSpawnSettings
      animals:
        ==: MVSpawnSubSettings
        spawn: 'true'
        spawnrate: '-1'
        exceptions: []
      monsters:
        ==: MVSpawnSubSettings
        spawn: 'false'
        spawnrate: '-1'
        exceptions: []
    entryfee:
      ==: MVEntryFee
      amount: '0.0'
      currency: '-1'
    hunger: 'true'
    autoHeal: 'true'
    adjustSpawn: 'true'
    portalForm: ALL
    gameMode: SURVIVAL
    keepSpawnInMemory: 'false'
    spawnLocation:
      ==: MVSpawnLocation
      x: 0.0
      y: 4.0
      z: 0.0
      pitch: 0.0
      yaw: 0.0
    autoLoad: 'true'
    bedRespawn: 'false'
    worldBlacklist: []
    environment: NORMAL
    seed: '8913251092162512362'
    generator: 'null'
    playerLimit: '-1'
    allowFlight: 'true'

```

The only other plugin that handles spawns that I use is Spawnz, but I am pretty sure it doesn't handle death respawns.
