### ISSUE TITLE
a big problem about generating a empty world as main world

### ISSUE THREAD

**Issue by i998979** [Multiverse/Multiverse-Core#1602]
hello
i have a problem for a while
the problem is:
i want to set my main world "world" that set in server.properties
and i load the world with emptyworldgenerator/ voidworld/ cleanroomgenerator plugin and the newest mv, build 691, 692
and after i generate the world, i delete it , then set the config in multiverse world.yml
i setted the world "world" generator to emptyworldgenerator/voidworld/cleanroomgenerator
then i load the server again
problem here
it still generate a normal world and just ignore my generator setting
and i tried to create a world by typing /mv create lobby normal -g EmptyWorldgenerator
it works
and all my server(bungeecord) got same problem
i can generate a empty world before
but after some day, i found out the world is started to generate

im using spigot 1.8.8 r01
multiverse build 692(for this bug test server), 697(all my server)
emptyworldgenerator 1.5

i hope the following information can help

```
Multiverse world.yml setting:
worlds:
  world:
    ==: MVWorld
    hidden: 'false'
    alias: world
    color: WHITE
    style: NORMAL
    pvp: 'true'
    scale: '1.0'
    respawnWorld: ''
    allowWeather: 'false'
    difficulty: NORMAL
    spawning:
      ==: MVSpawnSettings
      animals:
        ==: MVSpawnSubSettings
        spawn: 'false'
        spawnrate: '-1'
        exceptions: []
      monsters:
        ==: MVSpawnSubSettings
        spawn: 'false'
        spawnrate: '-1'
        exceptions: []
    entryfee:
      ==: MVEntryFee
      amount: '0.0'
      currency: '-1'
    hunger: 'true'
    autoHeal: 'true'
    adjustSpawn: 'true'
    portalForm: ALL
    gameMode: SURVIVAL
    keepSpawnInMemory: 'true'
    spawnLocation:
      ==: MVSpawnLocation
      x: 0.5
      y: 65.0
      z: 0.5
      pitch: 0.0
      yaw: 0.0
    autoLoad: 'true'
    bedRespawn: 'false'
    worldBlacklist: []
    environment: NORMAL
    seed: '6444048781545859232'
    generator: EmptyWorldGenerator
    playerLimit: '-1'
    allowFlight: 'false'
  world_the_end:
    ==: MVWorld
    hidden: 'false'
    alias: world_the_end
    color: WHITE
    style: NORMAL
    pvp: 'true'
    scale: '16.0'
    respawnWorld: ''
    allowWeather: 'false'
    difficulty: NORMAL
    spawning:
      ==: MVSpawnSettings
      animals:
        ==: MVSpawnSubSettings
        spawn: 'false'
        spawnrate: '-1'
        exceptions: []
      monsters:
        ==: MVSpawnSubSettings
        spawn: 'false'
        spawnrate: '-1'
        exceptions: []
    entryfee:
      ==: MVEntryFee
      amount: '0.0'
      currency: '-1'
    hunger: 'true'
    autoHeal: 'true'
    adjustSpawn: 'true'
    portalForm: ALL
    gameMode: SURVIVAL
    keepSpawnInMemory: 'true'
    spawnLocation:
      ==: MVSpawnLocation
      x: 0.5
      y: 65.0
      z: 0.5
      pitch: 0.0
      yaw: 0.0
    autoLoad: 'true'
    bedRespawn: 'false'
    worldBlacklist: []
    environment: THE_END
    seed: '6444048781545859232'
    generator: EmptyWorldGenerator
    playerLimit: '-1'
    allowFlight: 'false'
  world_nether:
    ==: MVWorld
    hidden: 'false'
    alias: world_nether
    color: WHITE
    style: NORMAL
    pvp: 'false'
    scale: '8.0'
    respawnWorld: ''
    allowWeather: 'false'
    difficulty: PEACEFUL
    spawning:
      ==: MVSpawnSettings
      animals:
        ==: MVSpawnSubSettings
        spawn: 'false'
        spawnrate: '-1'
        exceptions: []
      monsters:
        ==: MVSpawnSubSettings
        spawn: 'false'
        spawnrate: '-1'
        exceptions: []
    entryfee:
      ==: MVEntryFee
      amount: '0.0'
      currency: '-1'
    hunger: 'true'
    autoHeal: 'true'
    adjustSpawn: 'true'
    portalForm: ALL
    gameMode: SURVIVAL
    keepSpawnInMemory: 'true'
    spawnLocation:
      ==: MVSpawnLocation
      x: 0.5
      y: 65.0
      z: 0.5
      pitch: 0.0
      yaw: 0.0
    autoLoad: 'true'
    bedRespawn: 'false'
    worldBlacklist: []
    environment: NETHER
    seed: '6444048781545859232'
    generator: EmptyWorldGenerator
    playerLimit: '-1'
    allowFlight: 'false'
  testworld:
    ==: MVWorld
    hidden: 'false'
    alias: testworld
    color: WHITE
    style: NORMAL
    pvp: 'true'
    scale: '1.0'
    respawnWorld: ''
    allowWeather: 'false'
    difficulty: EASY
    spawning:
      ==: MVSpawnSettings
      animals:
        ==: MVSpawnSubSettings
        spawn: 'false'
        spawnrate: '-1'
        exceptions: []
      monsters:
        ==: MVSpawnSubSettings
        spawn: 'false'
        spawnrate: '-1'
        exceptions: []
    entryfee:
      ==: MVEntryFee
      amount: '0.0'
      currency: '-1'
    hunger: 'true'
    autoHeal: 'true'
    adjustSpawn: 'true'
    portalForm: ALL
    gameMode: SURVIVAL
    keepSpawnInMemory: 'true'
    spawnLocation:
      ==: MVSpawnLocation
      x: 0.5
      y: 65.0
      z: 0.5
      pitch: 0.0
      yaw: 0.0
    autoLoad: 'true'
    bedRespawn: 'false'
    worldBlacklist: []
    environment: NORMAL
    seed: '153773244610769742'
    generator: EmptyWorldGenerator
    playerLimit: '-1'
    allowFlight: 'false'
```

multiverse config.yml setting:

```
#  -------------------------------------------------------------------------  #
# This is the MV2 Config. If you mess it up, copy the values out              #
# delete it, and it will be regenerated. Then use the ingame interface        #
# to add your values back via the "/mv conf" command.                         #
# When in-game, simply type: "/mv conf ?" for help.                           #
# A config with explanations can be found here:                               #
# https://github.com/Multiverse/Multiverse-Core/wiki/config.yml               #
#                                                                             #
#                                                                             #
#  IMPORTANT !! IMPORTANT !! IMPORTANT !! IMPORTANT !! IMPORTANT !!IMPORTANT  #
#                                                                             #
# Do NOT delete this line from your config!!!!                                #
# ==: com.onarandombox.MultiverseCore.MultiverseCoreConfiguration             #
#                                                                             #
#  IMPORTANT !! IMPORTANT !! IMPORTANT !! IMPORTANT !! IMPORTANT !!IMPORTANT  #
#  -------------------------------------------------------------------------  #

multiverse-configuration:
  ==: com.onarandombox.MultiverseCore.MultiverseCoreConfiguration
  enforceaccess: 'false'
  prefixchat: 'false'
  prefixchatformat: '%chat%'
  useasyncchat: 'true'
  teleportintercept: 'true'
  firstspawnoverride: 'true'
  displaypermerrors: 'true'
  globaldebug: '0'
  silentstart: 'false'
  messagecooldown: '5000'
  version: '2.9'
  firstspawnworld: world
  teleportcooldown: '1000'
  defaultportalsearch: 'false'
  portalsearchradius: '128'
```

emptyworldgenerator config.yml setting:

```
# EmptyWorldGenerator v1.5 Config
#
# You can choose if the bedrock platform gets spawned or not.
# If enabled, there will be a platform of bedrock at the location specified
# below, and the player will spawn above it. If the option is
# disabled, there won't be any bedrock, but the player will still
# spawn above the location specified.
#
# You can set the radius of the rectangular bedrock platform.
# Example: If the radius is set to 0, a single block will spawn.
# If the radius is set to 1, a 3x3 platform will spawn (because it's
# one block on each side, as well as the center block). And so on..

bedrock:
  enabled: true
  x: 0
  y: 64
  z: 0
  radius: 0
```
