### ISSUE TITLE
Giants

### ISSUE THREAD

**Issue by rysroma** [Multiverse/Multiverse-Core#1608]
Hi,
I want a world where only giants can spawn, here are my settings:

``` yaml
      monsters:
        ==: MVSpawnSubSettings
        spawn: 'false'
        spawnrate: '-1'
        exceptions:
        - giant
```

this doesnt make giants spawn by /summon Giant. Spawn by this command works in worlds with monsters spawn true. I tried to find out how to enable giants but found no information about this. What am I doing wrong?
Thanks!
