### ISSUE TITLE
bPermissions, single world TP doesn't seem to be working.

### ISSUE THREAD

**Issue by srmorris2** [Multiverse/Multiverse-Core#1620]
Multiverse version 2.4
bPermissions 2.12
Developing a new small server, and wanting our default group to be able to jump between two worlds
<code>
    - multiverse.teleport.self.creative
    - multiverse.teleport.self.world
</code>

I'm only able to allow this group to teleport using the /mv tp command by giving them
<code>
    - multiverse.teleport.*
</code>

Full permissions file
```
default: default
groups:
  default:
    permissions:
    - bpermissions.spawn
    - commandbook.rules
    - commandbook.spawn
    - commandbook.time.check
    - multiverse.core.info
    - multiverse.core.list.worlds
    - multiverse.core.spawn.self
    - multiverse.core.tp.*
    - multiverse.core.tp.self
    - multiverse.teleport.*
    - multiverse.teleport.self.creative
    - multiverse.teleport.self.world
    groups: []
    meta:
      prefix: §4[Guest]§r
  student:
    permissions:
    - antibuild.bypass
    - commandbook.home.set
    - commandbook.home.teleport
    - commandbook.msg
    - commandbook.mute
    - commandbook.say
    - commandbook.say.me
    - commandbook.warp.list
    - commandbook.warp.teleport
    - worldedit.selection.*
    - worldguard.region.addmember.own.*
    - worldguard.region.addowner.own.*
    - worldguard.region.claim
    - worldguard.region.info.own.*
    - worldguard.region.removemember.own.*
    - worldguard.region.removeowner.own.*
    groups:
    - default
    meta:
      prefix: §4[CMS]§r
  staff:
    permissions:
    - commandbook.home.teleport
    - multiverse.teleport.self.world_nether
    - multiverse.teleport.self.world_the_end
    - worldguard.region.*
    groups:
    - default
    - student
    meta:
      prefix: §4§l[Staff]§r
  guest:
    permissions: []
    groups: []
```
