### ISSUE TITLE
Mansions, world vs world2 seeds, generation weirdness

### ISSUE THREAD

**Issue by aamche** [Multiverse/Multiverse-Core#1850]
After quite some testing it appears the default world seed effects mansion generation in other overworld dimensions.

Using a worlds file along the line of 

This seems to have problems with mansions in world2, this would have mansions missing. Also the server.properties seed would be 100. 

````
  world2:
    seed: '-755044858'
  
  world:
    seed: '100'
````

This seems to work

````
  world2:
    seed: '-755044858'
  
  world:
    seed: '-755044858'
````

Mansion Locations
````
-1976 -2040
-4728 -8296
-8504 -8440
5640 -920
11848 -8360
````

I'll keep running some world generations. And see if I can get a reliable pass/fail pattern.
