### ISSUE TITLE
Invalid portal destination

### ISSUE THREAD

**Issue by SlimeDog** [Multiverse/Multiverse-Core#1965]
Spigot 1.13.2 latest
Multiverse-Core version 3.0.0-b760
Multiverse-Portals version 3.0.0-b788

Per the [MV-Portals documentation](https://github.com/Multiverse/Multiverse-Portals/wiki/Command-Reference#wiki-create)
```
Destination can either another portal (p:portalname), world (w:worldname), position (e:WORLD:X,Y,Z[:PITCH:YAW]), or current position (here).
```
If I edit _portals.yml_ to specify
```
  lobby_blackdog:
    entryfee:
      amount: 0.0
    safeteleport: true
    teleportnonplayers: false
    handlerscript: ''
    owner: rambeau
    location: 2.0,4.0,-6.0:3.0,6.0,-6.0
    world: world_lobby
    destination: here
```
then on start-up, MV-Core reports
```
[06:12:16] [Server thread/WARN]: [Multiverse-Core] Portal lobby_blackdog has an invalid DESTINATION!
```
The _**here**_ destination works fine in-game (or at least, doesn't send the player elsewhere), but am I misreading the documentation?

Note that the destination cannot be set to _**here**_ with commands. For now, I changed it to explicit _**e:world_lobby:x,y,z**_ which is accepted by the parser.
