### ISSUE TITLE
Where does MV constantly get worlds?

### ISSUE THREAD

**Issue by Andre601** [Multiverse/Multiverse-Core#2235]
I used Multiverse-Core before but removed it from my server for some time (including the Multiverse-Core folder), but now when I want to re-add it, does it constantly load worlds that do not exist anymore.
Where does MV get the worlds from? The folders with the worlds are deleted and the MV folder is completely fresh.

This also gives me the issue, where I can't create a world with the desired name, because it "already exist" but I can also not remove it from the worlds.yml, because it doesn't exist anymore.
Is there a way to forcefully remove the entry from the config (and wherever information about it is also located)?

This is really an annoying situation that I'm unable to solve.

If there is no such force option would I appreciate if it could be added (i.e. `/mv remove <world_name> -f[orce]`

**Comment by benwoo1110** [comment]
You should delete the worlds.yml (other than server generated ones which will also be present no matter what) and reimport all your worlds using `/mvimport WORLDNAME WORLDTYPE` 

WORLDTYPE are normal, nether or end

**Comment by Andre601** [comment]
This wouldn't really help in my situation as
1. The worlds do no longer exist and I can't create them, because the name is already being used
2. I can delete the worlds.yml 100 times and MV will still load it with non-existant worlds, because it receives the information from *somewhere* that I don't know about.

**Comment by benwoo1110** [comment]
Can you send me your full server log?

Also it may be better for you to join mv discord:  https://discord.gg/NZtfKky

**Comment by Andre601** [comment]
https://paste.helpch.at/givamowivi.md

**Comment by benwoo1110** [comment]
### Reproducible issue due to conflict with Slime-World-Manager plugin

Even though there is no test2 world folder, but if have a test2.slime slime-worlds folder and in worlds.yml for SWM, it will result in mv showing that world test2 exist as unloaded.
```
# output of /mv list
[19:22:38 INFO]: ====[ Multiverse World List ]====
[19:22:38 INFO]: world_the_end - THE_END
[19:22:38 INFO]: world - NORMAL
[19:22:38 INFO]: world_nether - NETHER
[19:22:38 INFO]: test2 - UNLOADED
```


```
# Slime World Manager worlds.yml
worlds:
    test2:
        source: file
        spawn: 0, 64, 0
        difficulty: peaceful
        allowMonsters: true
        allowAnimals: true
        pvp: true
        environment: NORMAL
        worldType: DEFAULT
        loadOnStartup: true
        readOnly: false
```


![slime](https://user-images.githubusercontent.com/30431861/79977223-789f6f00-84d0-11ea-95a3-98eff1ea96d6.PNG)
