### ISSUE TITLE
Respawning always in one world

### ISSUE THREAD

**Issue by Dunuin** [Multiverse/Multiverse-Core#2244]
Hi,

I have 2 worlds each with own nether and end. My creative world is called "world" and my survival world is called "survival". I want the users to respawn in their beds in the world they die or at the worldspawn of the world they died if they didn't use a bed. But everytime someone dies they are respawned at the world spawn point of world "world" even if they die in world "survival" and used a bed.

I'm running Spigot 1.15.2 and my installed Mods are:
AdvancedAchievements.jar
AsyncWorldEdit-3.6.19.jar
Dynmap-3.0-beta-10-spigot.jar
EssentialsX-2.17.2.70.jar
EssentialsXAntiBuild-2.17.2.70.jar
EssentialsXChat-2.17.2.70.jar
EssentialsXGeoIP-2.17.2.70.jar
EssentialsXProtect-2.17.2.70.jar
EssentialsXSpawn-2.17.2.70.jar
EssentialsXXMPP-2.17.2.70.jar
Jobs4.15.7.jar
Multiverse-Core-4.1.1-SNAPSHOT.jar
Multiverse-Inventories-4.0.0-SNAPSHOT.jar
Multiverse-NetherPortals-4.1.1-SNAPSHOT.jar
Multiverse-Portals-4.1.1-SNAPSHOT.jar
Multiverse-SignPortals-4.1.1-SNAPSHOT.jar
Vault.jar
worldedit-bukkit-7.1.0.jar
worldguard-bukkit-7.0.2.jar

My /Multiverse-Core/config.yml is:
```
multiverse-configuration:
  ==: com.onarandombox.MultiverseCore.MultiverseCoreConfiguration
  enforceaccess: 'false'
  prefixchat: 'true'
  prefixchatformat: '[%world%]%chat%'
  useasyncchat: 'true'
  teleportintercept: 'true'
  firstspawnoverride: 'false'
  displaypermerrors: 'true'
  globaldebug: '0'
  silentstart: 'false'
  messagecooldown: '5000'
  version: '2.9'
  firstspawnworld: world
  teleportcooldown: '1000'
  defaultportalsearch: 'false'
  portalsearchradius: '128'
  autopurge: 'true'
  idonotwanttodonate: 'false'
```

My /Multiverse-Core/worlds.yml is:
```
worlds:
  survival_nether:
    ==: MVWorld
    hidden: 'false'
    alias: ''
    color: WHITE
    style: NORMAL
    pvp: 'false'
    scale: '8.0'
    respawnWorld: survival
    allowWeather: 'true'
    difficulty: NORMAL
    spawning:
      ==: MVSpawnSettings
      animals:
        ==: MVSpawnSubSettings
        spawn: 'true'
        spawnrate: '-1'
        exceptions: []
      monsters:
        ==: MVSpawnSubSettings
        spawn: 'true'
        spawnrate: '-1'
        exceptions: []
    entryfee:
      ==: MVEntryFee
      amount: '0.0'
    hunger: 'true'
    autoHeal: 'true'
    adjustSpawn: 'true'
    portalForm: ALL
    gameMode: SURVIVAL
    keepSpawnInMemory: 'true'
    spawnLocation:
      ==: MVSpawnLocation
      x: 7.0
      y: 66.0
      z: -1.0
      pitch: 0.0
      yaw: 0.0
    autoLoad: 'true'
    bedRespawn: 'true'
    worldBlacklist: []
    environment: NETHER
    seed: '3242343242'
    generator: 'null'
    playerLimit: '-1'
    allowFlight: 'false'
  world:
    ==: MVWorld
    hidden: 'false'
    alias: ''
    color: WHITE
    style: NORMAL
    pvp: 'false'
    scale: '1.0'
    respawnWorld: world
    allowWeather: 'true'
    difficulty: PEACEFUL
    spawning:
      ==: MVSpawnSettings
      animals:
        ==: MVSpawnSubSettings
        spawn: 'true'
        spawnrate: '-1'
        exceptions: []
      monsters:
        ==: MVSpawnSubSettings
        spawn: 'true'
        spawnrate: '-1'
        exceptions: []
    entryfee:
      ==: MVEntryFee
      amount: '0.0'
    hunger: 'false'
    autoHeal: 'true'
    adjustSpawn: 'true'
    portalForm: ALL
    gameMode: CREATIVE
    keepSpawnInMemory: 'true'
    spawnLocation:
      ==: MVSpawnLocation
      x: -16.0
      y: 64.0
      z: 252.0
      pitch: 0.0
      yaw: 0.0
    autoLoad: 'true'
    bedRespawn: 'true'
    worldBlacklist: []
    environment: NORMAL
    seed: '-3787163923921591113'
    generator: 'null'
    playerLimit: '-1'
    allowFlight: 'true'
  world_the_end:
    ==: MVWorld
    hidden: 'false'
    alias: ''
    color: WHITE
    style: NORMAL
    pvp: 'false'
    scale: '16.0'
    respawnWorld: world
    allowWeather: 'true'
    difficulty: PEACEFUL
    spawning:
      ==: MVSpawnSettings
      animals:
        ==: MVSpawnSubSettings
        spawn: 'true'
        spawnrate: '-1'
        exceptions: []
      monsters:
        ==: MVSpawnSubSettings
        spawn: 'true'
        spawnrate: '-1'
        exceptions: []
    entryfee:
      ==: MVEntryFee
      amount: '0.0'
    hunger: 'false'
    autoHeal: 'true'
    adjustSpawn: 'true'
    portalForm: ALL
    gameMode: CREATIVE
    keepSpawnInMemory: 'true'
    spawnLocation:
      ==: MVSpawnLocation
      x: 0.0
      y: 61.0
      z: 0.0
      pitch: 0.0
      yaw: 0.0
    autoLoad: 'true'
    bedRespawn: 'true'
    worldBlacklist: []
    environment: THE_END
    seed: '-3787163923921591113'
    generator: 'null'
    playerLimit: '-1'
    allowFlight: 'true'
  world_nether:
    ==: MVWorld
    hidden: 'false'
    alias: ''
    color: WHITE
    style: NORMAL
    pvp: 'false'
    scale: '8.0'
    respawnWorld: world
    allowWeather: 'true'
    difficulty: PEACEFUL
    spawning:
      ==: MVSpawnSettings
      animals:
        ==: MVSpawnSubSettings
        spawn: 'true'
        spawnrate: '-1'
        exceptions: []
      monsters:
        ==: MVSpawnSubSettings
        spawn: 'true'
        spawnrate: '-1'
        exceptions: []
    entryfee:
      ==: MVEntryFee
      amount: '0.0'
    hunger: 'false'
    autoHeal: 'true'
    adjustSpawn: 'true'
    portalForm: ALL
    gameMode: CREATIVE
    keepSpawnInMemory: 'true'
    spawnLocation:
      ==: MVSpawnLocation
      x: 7.0
      y: 66.0
      z: -1.0
      pitch: 0.0
      yaw: 0.0
    autoLoad: 'true'
    bedRespawn: 'true'
    worldBlacklist: []
    environment: NETHER
    seed: '-3787163923921591113'
    generator: 'null'
    playerLimit: '-1'
    allowFlight: 'true'
  survival:
    ==: MVWorld
    hidden: 'false'
    alias: ''
    color: WHITE
    style: NORMAL
    pvp: 'false'
    scale: '1.0'
    respawnWorld: survival
    allowWeather: 'true'
    difficulty: NORMAL
    spawning:
      ==: MVSpawnSettings
      animals:
        ==: MVSpawnSubSettings
        spawn: 'true'
        spawnrate: '-1'
        exceptions: []
      monsters:
        ==: MVSpawnSubSettings
        spawn: 'true'
        spawnrate: '-1'
        exceptions: []
    entryfee:
      ==: MVEntryFee
      amount: '0.0'
    hunger: 'true'
    autoHeal: 'true'
    adjustSpawn: 'true'
    portalForm: ALL
    gameMode: SURVIVAL
    keepSpawnInMemory: 'true'
    spawnLocation:
      ==: MVSpawnLocation
      x: -16.0
      y: 64.0
      z: 252.0
      pitch: 0.0
      yaw: 0.0
    autoLoad: 'true'
    bedRespawn: 'true'
    worldBlacklist: []
    environment: NORMAL
    seed: '3242343242'
    generator: 'null'
    playerLimit: '-1'
    allowFlight: 'false'
  survival_the_end:
    ==: MVWorld
    hidden: 'false'
    alias: ''
    color: WHITE
    style: NORMAL
    pvp: 'false'
    scale: '16.0'
    respawnWorld: survival
    allowWeather: 'true'
    difficulty: NORMAL
    spawning:
      ==: MVSpawnSettings
      animals:
        ==: MVSpawnSubSettings
        spawn: 'true'
        spawnrate: '-1'
        exceptions: []
      monsters:
        ==: MVSpawnSubSettings
        spawn: 'true'
        spawnrate: '-1'
        exceptions: []
    entryfee:
      ==: MVEntryFee
      amount: '0.0'
    hunger: 'true'
    autoHeal: 'true'
    adjustSpawn: 'true'
    portalForm: ALL
    gameMode: SURVIVAL
    keepSpawnInMemory: 'true'
    spawnLocation:
      ==: MVSpawnLocation
      x: 0.0
      y: 61.0
      z: 0.0
      pitch: 0.0
      yaw: 0.0
    autoLoad: 'true'
    bedRespawn: 'true'
    worldBlacklist: []
    environment: THE_END
    seed: '3242343242'
    generator: 'null'
    playerLimit: '-1'
    allowFlight: 'false'
```
The bed spawn location looks right if I look at the player files in /Multiverse-Inventories/worlds/survival/Dunuin.json:
`{"SURVIVAL":{"bedSpawnLocation":{"==":"org.bukkit.Location","world":"survival","x":-3.5,"y":63.0,"z":268.5,"pitch":0.0,"yaw":0.0}...`

Anyone knows what I'm doing wrong? I've read something online about respawn priorities with multiverse and worldguard/essentialsx?

Edit:
Looks like EssentialsXSpawn is overwriting the spawn setting of Multiverse. Removed it and spawning in beds now works.
