### ISSUE TITLE
Spawnpoints not working in some worlds

### ISSUE THREAD

**Issue by JustinBustin5** [Multiverse/Multiverse-Core#2300]
I'm trying to make an arena world where you spawn on a platform in the sky. I have the world spawn set there and the player spawnpoint and the Multiverse spawnpoint there, but when I die I respawn at a completely different location high enough in the air to die of fall damage.
It works properly in some other worlds, but not all.
Video: https://drive.google.com/file/d/1lm-2hqSfMeXL1UnrEtnN1rOjI9rN1Qrb/view?usp=sharing

**Comment by benwoo1110** [comment]
Do you have other hub/lobby plugins that alter spawn? Or essentialsXspawn?

Do send your full server startup log as well.

**Comment by JustinBustin5** [comment]
> Do you have other hub/lobby plugins that alter spawn? Or essentialsXspawn?
> 
> Do send your full server startup log as well.

I have EssentialsX, and I didn't know EssentialsXSpawn was a thing

**Comment by frambinni** [comment]
I had a similar problem, and changing these settings in `/plugins/Essentials/config.yml` solved it:
**Note:** `EssentialsXSpawn.jar` controls these settings, and will only take effect if you have it installed.
```yml
# What priority should we use for handling respawns?
# Set this to none, if you want vanilla respawning behaviour.
# Set this to lowest, if you want Multiverse to handle the respawning.
# Set this to high, if you want EssentialsSpawn to handle the respawning.
# Set this to highest, if you want to force EssentialsSpawn to handle the respawning.
respawn-listener-priority: lowest

# What priority should we use for handling spawning on joining the server?
# See respawn-listener-priority for possible values.
# Note: changing this may impact or break spawn-on-join functionality.
spawn-join-listener-priority: lowest
```

I also added this alias in `commands.yml` to override the Essentials `/spawn` command in favor of `/mv spawn`.
```yml
  spawn:
  - mv spawn $1-
```

So if you're *not* using `EssentialsXSpawn.jar`, then it's most likely a plugin that handles `/spawn` or your world/player spawn point that's conflicting with Multiverse.
