### ISSUE TITLE
I'm not able to respawn on the "respawnworld" set in config

### ISSUE THREAD

**Issue by nicquehen** [Multiverse/Multiverse-Core#240]
Hello,

When my member died on the world "Sprintcraft" they respawn on the default world (Servergame).

I want to change it by Sprintcraft but don't work :/ 

i run /mvm set respawn Sprintcraft

rb : 1337 
list of my plugin : http://s3.noelshack.com/uploads/images/14247276829830_20111113_015025.png

world.yml

```
  worlds:
  Sprintcraft:
    seed: 135174176
    environment: NORMAL
    alias:
      name: ''
    pvp: false
    fakepvp: false
    scale: 1.0
    allowweather: false
    difficulty: PEACEFUL
    animals:
      spawn: false
    monsters:
      spawn: false
    entryfee:
      amount: 0.0
      currency: -1
    hunger: false
    hidden: false
    gamemode: CREATIVE
    keepspawninmemory: true
    spawn:
      x: -489.0
      y: 81.0
      z: 243.0
      pitch: 0.0
      yaw: 0.0
    respawnworld: Sprintcraft
  pixelart:
    generator: CleanroomGenerator:10,stone,20,dirt,1,grass
    environment: NORMAL
    alias:
      name: ''
    pvp: false
    fakepvp: false
    scale: 1.0
    allowweather: false
    difficulty: PEACEFUL
    animals:
      spawn: false
    monsters:
      spawn: false
    entryfee:
      amount: 0.0
      currency: -1
    hunger: false
    hidden: false
    gamemode: CREATIVE
    keepspawninmemory: false
    spawn:
      x: 0.0
      y: 32.0
      z: 0.0
      pitch: 0.0
      yaw: 0.0
    respawnworld: pixelart
  Servergame_nether:
    environment: NETHER
    alias:
      name: ''
    pvp: true
    fakepvp: false
    scale: 8.0
    allowweather: true
    difficulty: EASY
    animals:
      spawn: true
    monsters:
      spawn: true
    entryfee:
      amount: 0.0
      currency: -1
    hunger: true
    hidden: false
    gamemode: SURVIVAL
    keepspawninmemory: true
    spawn:
      x: 73.5
      y: 64.0
      z: 47.5
      pitch: 0.0
      yaw: 0.0
  Servergame:
    environment: NORMAL
    alias:
      name: ''
    pvp: true
    fakepvp: false
    scale: 1.0
    allowweather: true
    difficulty: EASY
    animals:
      spawn: true
    monsters:
      spawn: true
    entryfee:
      amount: 0.0
      currency: -1
    hunger: true
    hidden: false
    gamemode: SURVIVAL
    keepspawninmemory: true
    spawn:
      x: -305.0
      y: 64.0
      z: 30.0
      pitch: 0.0
      yaw: 0.0
```
