### ISSUE TITLE
multiverse.access permission not being checked.

### ISSUE THREAD

**Issue by Psithief** [Multiverse/Multiverse-Core#328]
Multiverse-Core version: 2.2-b421
Craftbukkit: git-Bukkit-1.0.1-R1-b1597jnks
PEX 1.17
ButtonWarp 1.5.6

Negating `multiverse.access` does nothing. Anyone can go to any world, despite my config.
I turned on the debug mode in pex while teleporting between worlds with a buttonwarp. `multiverse.access` wasn't even being checked.

``` yaml
This is the MV2 Config. If you mess it up, copy the values out
Delete it, and it will be regenerated. Then use the ingame interface
to add your values back.
A config with explanations can be found here:
https://github.com/Multiverse/Multiverse-Core/wiki/config.yml

worldnameprefix: false
enforceaccess: true
enforcegamemodes: true
bedrespawn: false
version: 2.4
displaypermerrors: true
messagecooldown: 5000
opfallback: false
debug: 0
teleportcooldown: NOT SET
```
