### ISSUE TITLE
Makes server not respond

### ISSUE THREAD

**Issue by ghost** [Multiverse/Multiverse-Core#337]
Problem
Sometimes when i start up my server it says it done but i type in /ping and it doesn't respond i cant log in or any thing.

it works sometimes when i delete it and download a new multiverse but then the next day it stops working again.

Startup log (Code formatted with 4 spaces)
No errors...

Any other relevant files:
Here is my permissions file for PermissionsEx:

```
users:
    doggyroc:
        group:
        - Admin
    thesnowyowl:
        group:
        - Admin
    Zafalron:
        group:
        - Donater+
    rkak12345:
        group:
        - New
    diamonde_digger:
        group:
        - New
    leithal7:
        group:
        - New
groups:
    New:
        default: true
        permissions:
        - modifyworld.login
        - spamhammer.ignore
        - -'*'
        prefix: '&8[&7New&8]&f'
    Prebuilder:
        default: false
        permissions:
        - -'*'
        - modifyworld.login
        - modifyworld.chat
        - VIP.1
        - multiverse.access.*
        - -multiverse.access.survivalmap
        worlds:
            Creative:
                permissions:
                - modifyworld.*
                - -modifyworld.blocks.destroy.bedrock
        prefix: '&1[&8Builder&1]&f'
    Builder:
        default: false
        permissions:
        - modifyworld.*
        - -modifyworld.blocks.place.bedrock
        - multihome.namedhome.set
        - multihome.namedhome.go
        - multihome.namedhome.delete
        - multihome.namedhome.list
        - multihome.defaulthome.go
        - multihome.defaulthome.set
        - reporter.report
        - mailbox.user.send
        - iConomy.user
        - multiverse.access.*
        - -multiverse.access.survivalmap
        - lottery.buy
        - battlenight.user
        - ChestShop.shop.create
        - ChestShop.shop.buy
        - ChestShop.shop.sell
        - commandbook.spawn
        - commandbook.warp.teleport
        - VIP.1
        prefix: '&8[&1Builder&8]&f'
        worlds:
            Creative:
                permissions:
                - -modifyworld.blocks.destroy.bedrock
            Survival:
                permissions:
                - modifyworld.*
    Veteran:
        default: false
        inheritance:
        - Builder
        permissions:
        - VIP.2
        prefix: '&8[&3Veteran&8]&f'
    VIP:
        default: false
        inheritance:
        - Builder
        permissions:
        - multiverse.access.survivalmap
        - VIP.2
        prefix: '&0[&6VIP&0]&f'
        worlds:
            SurvivalMap:
                permissions:
                - -'*'
                - modifyworld.*
            Nether:
                permissions: null
            Creative:
                permissions:
                - -modifyworld.blocks.destroy.bedrock
    EpicBuilder:
        default: false
        inheritance:
        - Builder
        - VIP.3
        permissions: null
        prefix: '&7[&2Epic Builder&7]&f'
    RedstoneExpert:
        default: false
        prefix: '&7[&4Redstone Expert&7]&f'
        inheritance:
        - Builder
        - VIP.3
        permissions: null
    Soldier:
        default: false
        prefix: '&7[&0Soldier&7]&f'
        inheritance:
        - Builder
        - VIP.3
        permissions: null
    Donator:
        default: false
        prefix: '&d[&5Donater&d]&f'
        inheritance:
        - Builder
        permissions:
        - blockhat.hat
        - VIP.5
    Donator+:
        default: false
        prefix: '&5[&dDonater+&5]&f'
        inheritance:
        - Builder
        - Donator
        permissions:
        - cf.allowfly
        - nocheat.checks.moving
        - VIP.8
    Sponser:
        default: false
        inheritance:
        - Builder
        - Donator
        - Donator+
        permissions:
        - VIP.10
        prefix: '&0[&4S&ap&2o&9n&5s&de&er&0]&f'
    Trainee:
        default: false
        inheritance:
        - Builder
        permissions:
        - VIP.7
        prefix: '&f[&8Trainee&8]&f'
    Mod:
        default: false
        inheritance:
        - Builder
        - VIP
        - EpicBuilder
        - RedstoneExpert
        - Soldier
        permissions:
        - bukkit.command.teleport
        - bukkit.command.ban.player
        - bukkit.command.unban.player
        - bukkit.command.kick
        - bukkit.command.help
        - spamhammer.unmute
        - spamhammer.ignore
        - reporter.list
        - reporter.view
        - reporter.request
        - reporter.complete
        - reporter.delete
        - reporter.respond
        - iConomy.plus
        - adminchat.send
        - adminchat.read
        - autokick.nokick
        - goinround.scan
        - goinround.ignore
        - srpex.setrank.vip
        - srpex.setrank.builder
        - srpex.setrank.new
        - worldedit.*
        - glowstonelanterns.gl
        - glowstonelanterns.destroyLanterns
        - ChestShop.mod
        - discosheep.party.many
        - discosheep.mob.sheep
        - discosheep.color
        - discosheep.stop
        - ice.ipban
        - lagmeter.*
        - lottery.buy
        - mobdisguise.*
        - OpenInv.openinv
        - OpenInv.search
        - OpenInv.crossworld
        - OpenInv.exempt
        - OpenInv.anychest
        - SignClock.build
        - vanish.see
        - vanish.vanish
        - vanish.nopickup
        - vanish.nofollow
        - vanish.nointeract
        - vanish.preventincomingdamage
        - vanish.preventoutgoingdamage
        - vanish.fakeannounce
        - vanish.statusupdates
        - vanish.toggle
        - cf.allowfly
        - commandbook.warp.set
        - commandbook.broadcast
        - commandbook.mute
        - commandbook.slap
        - commandbook.slap.other
        - commandbook.rocket
        - commandbook.rocket.other
        - commandbook.barrage
        - commandbook.barrage.other
        - commandbook.shock
        - commandbook.shock.other
        - commandbook.thor
        - CommandSigns.*
        - VIP.10
        prefix: '&0[&fMod&0]&f'
    Admin:
        default: false
        permissions:
        - -vanish.hooks.dynmap.alwayshidden
        - -vanish.silentjoin
        - -vanish.silentquit
        - '*'
        prefix: '&6[&0Admin&6]&f'
```
