### ISSUE TITLE
Permission Nodes not working?

### ISSUE THREAD

**Issue by 22alec22** [Multiverse/Multiverse-Core#431]
Hey so i love the plugin, but it appears as if the permission nodes are not working for me. I do not want to allow everyone to enter the creative portal, but at the moment i have to because i need to set it to ignore permissions in the config file. I am having the same problem with globalshop. I'm not entirely sure if it is this plugin specifically. I will post a copy of my permission file here:            (If you see any issues that may be causing it please point them out)

``` yaml
groups:
    guest:
        default: false
        info:
            build: true
        permissions: []
    member:
        default: true
        info:
            build: true
            prefix: '[&2Member&f] '
        permissions:
        - essentials.who
        - essentials.help
        - essentials.home
        - essentials.motd
        - essentials.rules
        - essentials.sethome
        - essentials.spawn
        - essentials.msg
        - essentials.list
        - multiverse.access.world
        - multiverse.access.world_nether
        - multiverse.access.world_the_end
        - multiverse.access.creative
        - multiverse.access.survival
        - multiverse.portal.access.spawn
        - multiverse.portal.access.spawn2
        - multiverse.portal.access.creative
        - multiverse.portal.access.survival
        - globalshop.trade.*
        inheritance:
        - guest
    VIP:
        default: false
        info:
            build: true
            prefix: '[&2VIP&f] '
        permissions:
        - essentials.warp
        - essentials.setwarp
        - essentials.kit
        - essentials.kit.vip
        - essentials.kit.tools
        inheritance:
        - member
    mod:
        default: false
        info:
            build: true
            prefix: '[&5Mod&f] '
        permissions:
        - essentials.tp
        - essentials.tphere
        - essentials.god
        - essentials.kick
        - essentials.mute
        - essentials.tppos
        - essentials.jump
        - essentials.delhome
        - essentials.delwarp
        - essentials.unbanip
        - essentials.unban
        - essentials.tempban
        - essentials.sudo
        - essentials.socialspy
        - essentials.kill
        - essentials.invsee
        - essentials.clearinventory
        - essentials.banip
        - essentials.ban
        - essentials.whois
        - essentials.seen
        - essentials.realname
        - essentials.warp
        - essentials.setwarp
        - essentials.list
        inheritance:
        - member
    admin:
        default: false
        info:
            build: true
            prefix: '[&4Admin&f] '
        permissions:
        - '*'
        - simpleprefix.admin
        inheritance:
        - mod
    owner:
        default: false
        info:
            build: true
            prefix: '[&6Owner&f] '
        permissions: []
        inheritance:
        - admin
```

It is normally more spaced out, but the text box on here appears to flatten it all out.
