### ISSUE TITLE
per world build permissions

### ISSUE THREAD

**Issue by maddavo** [Multiverse/Multiverse-Core#497]
I just cannot get my head around this and I fear I may strangle a cat.

So the situation is:
- craftbukkit 1.1R3
- Multiverse-Core
- Multiverse-Portals
- Multiverse-NetherPortals
- PermissionsBukkit 1.1

I have several worlds.  I want players to be able to build in some and not in others.  Basically, all players are in the default group and I have set permissions.build to TRUE.  Then on the worlds I want to anti-build I have set permissions.build to FALSE.  My PermissionsBukkit/config.yml is below.

PROBLEM:  The build permission does not seem to change when going through a portal.  ie: start on a world where you can build - go through a portal to a world you cannot build - you can still build.  Reload permissions (/perms reload).  Then you can't build (as you shouldn't be able to).  BUT - go through a portal to a world where you should be able to build - you still can't build.

plugins/PermissionsBukkit/config.yml

``` yaml
users:
    MadDavo:
        groups:
        - admin
groups:
    default:
        permissions:
            multiverse.access.*: true
            multiverse.help: false
            multiverse.portal.access.*: true
            permissions.build: true
        worlds:
            Lobby:
                permissions.build: false
            skyblockstart:
                permissions.build: false
    admin:
        permissions:
            multiverse.*: true
            multiverse.portal.*: true
            permissions.*: true
            permissions.build: true
        inheritance:
        - default
messages:
    build: '&cYou do not have permission to build here.'
```

I must admit I have not yet tried mvtp a player to see the behaviour.

This smells more of a Multiverse or Multiverse-Portals issue rather than a perms issue.

I HAVE also tried giving the default user permissions.build FALSE and then giving world permissions.build TRUE on the worlds I want to let the build in.  SAME behaviour.

Cheers,
Maddavo
