### ISSUE TITLE
Snow Golems

### ISSUE THREAD

**Issue by Valdiralita** [Multiverse/Multiverse-Core#513]
If you set 

```
...
spawn-animals=false
...
```

in the server.properties but enable mob spawning in the MV config 

``` yaml
monsters:
      spawn: true
animals:
      spawn: true
```

you cant build snow golems, while hostile and neutral mobs spawn

regards Valdiralita
