### ISSUE TITLE
Players gets tele to spawn when server restarts! Help

### ISSUE THREAD

**Issue by rocky143** [Multiverse/Multiverse-Core#552]
I tried looking in the config.yml file but could not find some thing regarding to the issue and the problem I'm having is when my server restarts every one gets tped to spawn point except admins/op and I'm also using essentials spawn but it never did this before but now its doing it. Please help! 
Also I tried giving one of my use multiverse.\* command for him to try what happens and it worked fine he did not get tped to spawn so what is the permission note i shell give to prevent people to spawn at spawn when the server restarts?

This is how my config looks like but still not working....

```
multiverse-configuration:
  ==: com.onarandombox.MultiverseCore.MultiverseCoreConfiguration
  enforceaccess: 'false'
  prefixchat: 'false'
  teleportintercept: 'true'
  firstspawnoverride: 'false'
  displaypermerrors: 'true'
  globaldebug: '0'
  messagecooldown: '5000'
  version: '2.9'
  firstspawnworld: 
  teleportcooldown: '1000'
``
```
