### ISSUE TITLE
New Players Wrong Destination

### ISSUE THREAD

**Issue by jones989** [Multiverse/Multiverse-Core#616]
So I built two portals and created and linked them together exactly like on your wiki with the p:portal1 and the /mv select. It works for me, but when a new person joins the server and uses the portal, it takes them somewhere COMPLETELY different to where i linked the portal. If the person then goes back to spawn and uses it again, it takes them to the right place.

This is my portal.yml just incase you need it:

```
portals:
  ShopPort1:
    entryfee:
      currency: -1
      amount: 0.0
    safeteleport: true
    teleportnonplayers: false
    owner: jones989
    location: 109.0,65.0,170.0:113.0,69.0,170.0
    world: Cath
    destination: p:ShopPort2
  ShopPort2:
    entryfee:
      currency: -1
      amount: 0.0
    safeteleport: true
    teleportnonplayers: false
    owner: jones989
    location: -51.0,33.0,67.0:-44.0,38.0,67.0
    world: shop
    destination: p:ShopPort1
  MainPort1:
    entryfee:
      currency: -1
      amount: 0.0
    safeteleport: true
    teleportnonplayers: false
    owner: jones989
    location: 66.0,65.0,154.0:66.0,69.0,157.0
    world: Cath
    destination: p:MainPort2
  MainPort2:
    entryfee:
      currency: -1
      amount: 0.0
    safeteleport: true
    teleportnonplayers: false
    owner: jones989
    location: 272.0,67.0,64.0:275.0,70.0,64.0
    world: worldM
    destination: p:MainPort1
  PvPPort1:
    entryfee:
      currency: -1
      amount: 0.0
    safeteleport: true
    teleportnonplayers: false
    owner: jones989
    location: 156.0,65.0,154.0:156.0,69.0,157.0
    world: Cath
    destination: p:PvPPort2
  PvPPort2:
    entryfee:
      currency: -1
      amount: 0.0
    safeteleport: true
    teleportnonplayers: false
    owner: jones989
    location: 290.0,4.0,415.0:293.0,8.0,415.0
    world: worldP2
    destination: p:PvPPort1
  FactionPort1:
    entryfee:
      currency: -1
      amount: 0.0
    safeteleport: true
    teleportnonplayers: false
    owner: jones989
    location: 77.0,65.0,262.0:77.0,69.0,265.0
    world: Cath
    destination: p:FactionPort2
  FactionPort2:
    entryfee:
      currency: -1
      amount: 0.0
    safeteleport: true
    teleportnonplayers: false
    owner: jones989
    location: 236.0,64.0,139.0:239.0,67.0,139.0
    world: worldF
    destination: p:FactionPort1
```
