### ISSUE TITLE
Wrong mobs in Nether

### ISSUE THREAD

**Issue by icemanxp** [Multiverse/Multiverse-Core#718]
So I'm having an issue where the mobs that spawn in nether are wrong (Skeletons, Creepers, Zombies).
I've verified that the world is being loaded as a Nether environment in both the bukkit startup log and with /mv list
I currently have two Nether worlds, each associated with a regular world, both are affected.
I have the following Mods installed:
CraftIRC
Essentials
MultiInv
Multiverse-Core-2.4
Multiverse-NetherPortals-2.4
PermissionsEx
SimplePlayerList
Vault
WormholeXTreme

Here is my Muliverse world.yml:

``` YAML
worlds:
  creative:
    gamemode: CREATIVE
    keepspawninmemory: false
    scale: 1.0
    animals:
      spawn: true
    pvp: true
    entryfee:
      amount: 0.0
      currency: -1
      price: 0.0
    alias:
      color: WHITE
      name: ''
    allowweather: true
    monsters:
      spawn: false
    spawn:
      yaw: 0.0
      pitch: 0.0
      z: 237.5
      y: 64.0
      x: -82.5
      world: creative
    environment: NORMAL
    respawnworld: creative
    tempspawn: ''
    seed: 8288430885116527608
    difficulty: EASY
    hunger: true
    hidden: false
    autoheal: true
    adjustspawn: true
    autoload: true
    bedrespawn: true
    type: NORMAL
    portalform: ALL
  world_nether:
    gamemode: SURVIVAL
    keepspawninmemory: false
    scale: 8.0
    animals:
      spawn: true
    pvp: true
    entryfee:
      amount: 0.0
      currency: -1
      price: 0.0
    alias:
      color: WHITE
      name: ''
    allowweather: true
    monsters:
      spawn: true
    spawn:
      yaw: 0.0
      pitch: 0.0
      z: 100.5
      y: 63.0
      x: 107.5
      world: world_nether
    environment: NETHER
    respawnworld: world
    tempspawn: ''
    seed: 1874124929154342117
    difficulty: EASY
    hunger: true
    hidden: false
    autoheal: true
    adjustspawn: true
    autoload: true
    bedrespawn: true
    type: NORMAL
    portalform: ALL
  survivedan:
    gamemode: SURVIVAL
    keepspawninmemory: false
    scale: 1.0
    animals:
      spawn: true
    pvp: true
    entryfee:
      amount: 0.0
      currency: -1
      price: 0.0
    alias:
      color: WHITE
      name: ''
    allowweather: true
    monsters:
      spawn: true
    spawn:
      yaw: 0.0
      pitch: 0.0
      z: 4.5
      y: 64.0
      x: 101.5
      world: survivedan
    environment: NORMAL
    respawnworld: survivedan
    tempspawn: ''
    seed: -3782475465935354339
    difficulty: EASY
    hunger: true
    hidden: false
    autoheal: true
    adjustspawn: true
    autoload: true
    bedrespawn: true
    type: NORMAL
    portalform: ALL
  survival:
    gamemode: SURVIVAL
    keepspawninmemory: false
    scale: 1.0
    animals:
      spawn: true
    pvp: true
    entryfee:
      amount: 0.0
      currency: -1
      price: 0.0
    alias:
      color: WHITE
      name: ''
    allowweather: true
    monsters:
      spawn: true
    spawn:
      yaw: 0.0
      pitch: 0.0
      z: 378.5
      y: 74.0
      x: -201.5
      world: survival
    environment: NORMAL
    respawnworld: survival
    tempspawn: ''
    seed: -5474949181196486131
    difficulty: EASY
    hunger: true
    hidden: false
    autoheal: true
    adjustspawn: true
    autoload: true
    bedrespawn: true
    type: NORMAL
    portalform: ALL
  world:
    gamemode: CREATIVE
    keepspawninmemory: false
    scale: 1.0
    animals:
      spawn: true
    pvp: true
    entryfee:
      amount: 0.0
      currency: -1
      price: 0.0
    alias:
      color: WHITE
      name: ''
    allowweather: true
    monsters:
      spawn: false
    spawn:
      yaw: 0.0
      pitch: 0.0
      z: -86.5
      y: 64.0
      x: -313.5
      world: world
    environment: NORMAL
    respawnworld: world
    tempspawn: ''
    seed: 1874124929154342117
    difficulty: EASY
    hunger: true
    hidden: false
    autoheal: true
    adjustspawn: true
   autoload: true
    bedrespawn: true
    type: NORMAL
    portalform: ALL
  air:
    gamemode: CREATIVE
    keepspawninmemory: false
    scale: 1.0
    animals:
      spawn: true
    pvp: true
    entryfee:
      amount: 0.0
      currency: -1
      price: 0.0
    alias:
      color: WHITE
      name: ''
    allowweather: true
    monsters:
      spawn: true
    spawn:
      yaw: 0.0
      pitch: 0.0
      z: 74.5
      y: 63.0
      x: 35.5
      world: air
    environment: NORMAL
    respawnworld: ''
    tempspawn: ''
    seed: 4407422740521290816
    difficulty: EASY
    hunger: true
    hidden: false
    autoheal: true
    adjustspawn: true
    autoload: true
    bedrespawn: true
    type: NORMAL
    portalform: ALL
  dragonsreach:
    keepspawninmemory: true
    gamemode: SURVIVAL
    scale: 1.0
    animals:
      spawn: true
    pvp: true
    entryfee:
      amount: 0.0
      currency: -1
      price: 0.0
    alias:
      color: WHITE
      name: ''
    seed: 1827087020
    allowweather: true
    difficulty: EASY
    monsters:
      spawn: true
    hunger: true
    spawn:
      yaw: 0.0
      pitch: 0.0
      z: 93.5
      y: 71.0
      x: 240.5
      world: dragonsreach
    environment: NORMAL
    respawnworld: ''
    tempspawn: ''
    hidden: false
    autoheal: true
    adjustspawn: true
    autoload: true
    bedrespawn: true
    type: NORMAL
    portalform: ALL
  world_the_end:
    seed: 1874124929154342117
    environment: THE_END
    hidden: false
    alias:
      name: ''
      color: WHITE
    pvp: true
    scale: 1.0
    respawnworld: ''
    allowweather: true
    difficulty: EASY
    animals:
      spawn: true
    monsters:
      spawn: true
    entryfee:
      currency: -1
      price: 0.0
    hunger: true
    autoheal: true
    adjustspawn: true
    gamemode: SURVIVAL
    keepspawninmemory: true
    spawn:
      x: 2.5
      y: 64.0
      z: 1.5
      pitch: 0.0
      yaw: 0.0
      world: world_the_end
    autoload: true
    bedrespawn: true
    type: NORMAL
    portalform: ALL
  dragonsreach_the_end:
    seed: 682699494
    environment: THE_END
    hidden: false
    alias:
      name: ''
      color: WHITE
    pvp: true
    scale: 1.0
    respawnworld: ''
    allowweather: true
    difficulty: EASY
    animals:
      spawn: true
    monsters:
      spawn: true
    entryfee:
      currency: -1
      price: 0.0
    hunger: true
    autoheal: true
    adjustspawn: true
    gamemode: SURVIVAL
    keepspawninmemory: true
    spawn:
      x: 0.0
      y: 62.0
      z: 0.0
      pitch: 0.0
      yaw: 0.0
      world: dragonsreach_the_end
    autoload: true
    bedrespawn: true
    type: NORMAL
    portalform: ALL
  dragonsreach_nether:
    seed: -6593970506210273389
    environment: NETHER
    type: NORMAL
    hidden: false
    alias:
      name: ''
      color: WHITE
    pvp: true
    scale: 8.0
    respawnworld: ''
    allowweather: true
    difficulty: EASY
    animals:
      spawn: true
    monsters:
      spawn: true
    entryfee:
      currency: -1
      price: 0.0
    hunger: true
    autoheal: true
    adjustspawn: true
    portalform: ALL
    gamemode: SURVIVAL
    keepspawninmemory: true
    spawn:
      x: -3.0
      y: 65.0
      z: 12.0
      pitch: 0.0
      yaw: 0.0
      world: dragonsreach_nether
    autoload: true
    bedrespawn: true
```
