### ISSUE TITLE
the "spawning animals exception" do not really work

### ISSUE THREAD

**Issue by Ardragoon** [Multiverse/Multiverse-Core#872]
```
 animals:
    ==: MVSpawnSubSettings
    spawn: 'true'
    exceptions:
    - ozelot
```

this means every animal spawns but NO ozelot.

ozelots still spawn. 

if i set this to 
     animals:
        ==: MVSpawnSubSettings
        spawn: 'false'
        exceptions:
        - cow
        - chicken
        - sheep
        - pig

nothing spawns.... and if i set a spawn egg i or users arent able to get baby animals. the love mode works but the babys dont spawn. 
and the second thing is that in my building world (flat world) are thousands of ozelots oO

thx for listening ; ) 

greets
Ardragoon
